### ISSUE TITLE
Archive for previous events?

### ISSUE THREAD

**Issue by ZoeBijl** [role-drinks/roledrinks.nl#4]

**Comment by lassediercks** [comment]
I actually took multiple looks at the website afterwards to see who has attended and to get the names right. I'd love to keep the possibility to do that

**Comment by StommePoes** [comment]
++ Although it would also need some updating as some who said they'd come didn't, and vice versa.

**Comment by ZoeBijl** [comment]
They could just be HTML pages link to from some Archive index page. We would need to make some sort of menu in the header though.

**Comment by ZoeBijl** [comment]
This is now done on the new website: http://roledrinks.com
